# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI/UiFiles/LocalAnalysisDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LocalAnalysisDialog(object):
    def setupUi(self, LocalAnalysisDialog):
        LocalAnalysisDialog.setObjectName("LocalAnalysisDialog")
        LocalAnalysisDialog.resize(400, 300)
        self.buttonBox = QtWidgets.QDialogButtonBox(LocalAnalysisDialog)
        self.buttonBox.setGeometry(QtCore.QRect(30, 240, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.browse_button = QtWidgets.QPushButton(LocalAnalysisDialog)
        self.browse_button.setGeometry(QtCore.QRect(110, 90, 161, 23))
        self.browse_button.setObjectName("browse_button")
        self.label = QtWidgets.QLabel(LocalAnalysisDialog)
        self.label.setGeometry(QtCore.QRect(30, 90, 111, 16))
        self.label.setObjectName("label")
        self.analyze_button = QtWidgets.QPushButton(LocalAnalysisDialog)
        self.analyze_button.setGeometry(QtCore.QRect(300, 90, 75, 21))
        self.analyze_button.setObjectName("analyze_button")

        self.retranslateUi(LocalAnalysisDialog)
        self.buttonBox.accepted.connect(LocalAnalysisDialog.accept)
        self.buttonBox.rejected.connect(LocalAnalysisDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(LocalAnalysisDialog)

    def retranslateUi(self, LocalAnalysisDialog):
        _translate = QtCore.QCoreApplication.translate
        LocalAnalysisDialog.setWindowTitle(_translate("LocalAnalysisDialog", "Local Analysis"))
        self.browse_button.setText(_translate("LocalAnalysisDialog", "Browse..."))
        self.label.setText(_translate("LocalAnalysisDialog", "Dataset File"))
        self.analyze_button.setText(_translate("LocalAnalysisDialog", "Analyze"))
