# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI/UiFiles/MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sys

from PyQt5.QtCore import *
from PyQt5.QtWidgets import *

from Client.UI.PyFiles.UploadDataDialog import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(696, 380)
        MainWindow.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.title = QtWidgets.QLabel(self.centralwidget)
        self.title.setGeometry(QtCore.QRect(280, 40, 631, 81))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(30)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.title.setFont(font)
        self.title.setObjectName("title")
        self.upload_data_button = QtWidgets.QPushButton()
        self.upload_data_button.setGeometry(QtCore.QRect(70, 130, 131, 81))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.upload_data_button.setFont(font)
        self.upload_data_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.upload_data_button.setObjectName("upload_data_button")

        set_style(self)
        self.create_experiment_button = QtWidgets.QPushButton()
        self.create_experiment_button.setGeometry(QtCore.QRect(400, 130, 241, 81))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.create_experiment_button.setFont(font)
        self.create_experiment_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.create_experiment_button.setObjectName("create_experiment_button")

        self.view_results_button = QtWidgets.QPushButton()
        self.view_results_button.setGeometry(QtCore.QRect(460, 250, 131, 81))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.view_results_button.setFont(font)
        self.view_results_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.view_results_button.setObjectName("view_results_button")

        self.simulations_button = QtWidgets.QPushButton()
        self.simulations_button.setGeometry(QtCore.QRect(80, 250, 131, 81))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.simulations_button.setFont(font)
        self.simulations_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.simulations_button.setObjectName("simulations_button")

        self.main_grid = QGridLayout()
        self.main_grid.setHorizontalSpacing(50)
        self.main_grid.setContentsMargins(QMargins(50, 50, 50, 50))

        self.main_grid.addWidget(self.upload_data_button, 1, 1, 1, 1)
        self.main_grid.addWidget(self.create_experiment_button, 1, 3, 1, 1)

        self.main_grid.addWidget(self.view_results_button, 2, 1, 1, 1)
        self.main_grid.addWidget(self.simulations_button, 2, 3, 1, 1)

        self.centralwidget.setLayout(self.main_grid)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ASY Experiment Tool"))
        self.title.setText(_translate("MainWindow", "ASY protocol experiment tool"))
        self.upload_data_button.setText(_translate("MainWindow", "Upload data"))
        self.create_experiment_button.setText(_translate("MainWindow", "Create new experiment"))
        self.view_results_button.setText(_translate("MainWindow", "View Results"))
        self.simulations_button.setText(_translate("MainWindow", "Simulations"))


if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    window = QtWidgets.QMainWindow()
    MyWindow = Ui_MainWindow()
    set_style(app)
    # setup stylesheet

    MyWindow.setupUi(window)
    MyWindow.retranslateUi(window)
    window.show()
    sys.exit(app.exec_())
