# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI/UiFiles/NewExperimentDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_NewExperimentDialog(object):
    def setupUi(self, NewExperimentDialog):
        NewExperimentDialog.setObjectName("NewExperimentDialog")
        NewExperimentDialog.setWindowModality(QtCore.Qt.WindowModal)
        NewExperimentDialog.resize(400, 300)
        self.buttonBox = QtWidgets.QDialogButtonBox(NewExperimentDialog)
        self.buttonBox.setGeometry(QtCore.QRect(30, 240, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label = QtWidgets.QLabel(NewExperimentDialog)
        self.label.setGeometry(QtCore.QRect(40, 110, 151, 16))
        self.label.setObjectName("label")
        self.experiment_name_textbox = QtWidgets.QTextEdit(NewExperimentDialog)
        self.experiment_name_textbox.setGeometry(QtCore.QRect(190, 100, 104, 41))
        self.experiment_name_textbox.setObjectName("experiment_name_textbox")

        self.retranslateUi(NewExperimentDialog)
        self.buttonBox.accepted.connect(NewExperimentDialog.accept)
        self.buttonBox.rejected.connect(NewExperimentDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(NewExperimentDialog)

    def retranslateUi(self, NewExperimentDialog):
        _translate = QtCore.QCoreApplication.translate
        NewExperimentDialog.setWindowTitle(_translate("NewExperimentDialog", "Create New Experiment"))
        self.label.setText(_translate("NewExperimentDialog", "Experiment Name:"))
