# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI/UiFiles/SimulationsDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SimulationsDialog(object):
    def setupUi(self, SimulationsDialog):
        SimulationsDialog.setObjectName("SimulationsDialog")
        SimulationsDialog.resize(860, 596)
        self.verticalLayout = QtWidgets.QVBoxLayout(SimulationsDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.form_layout = QtWidgets.QFormLayout()
        self.form_layout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.form_layout.setObjectName("form_layout")
        self.label_2 = QtWidgets.QLabel(SimulationsDialog)
        self.label_2.setObjectName("label_2")
        self.form_layout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.num_of_parties_textbox = QtWidgets.QLineEdit(SimulationsDialog)
        self.num_of_parties_textbox.setObjectName("num_of_parties_textbox")
        self.form_layout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.num_of_parties_textbox)
        self.label_3 = QtWidgets.QLabel(SimulationsDialog)
        self.label_3.setObjectName("label_3")
        self.form_layout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.num_of_runs_textbox = QtWidgets.QLineEdit(SimulationsDialog)
        self.num_of_runs_textbox.setObjectName("num_of_runs_textbox")
        self.form_layout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.num_of_runs_textbox)
        self.generate_dataset_checkbox = QtWidgets.QCheckBox(SimulationsDialog)
        self.generate_dataset_checkbox.setChecked(True)
        self.generate_dataset_checkbox.setObjectName("generate_dataset_checkbox")
        self.form_layout.setWidget(4, QtWidgets.QFormLayout.SpanningRole, self.generate_dataset_checkbox)
        self.label = QtWidgets.QLabel(SimulationsDialog)
        self.label.setObjectName("label")
        self.form_layout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label)
        self.browse_button = QtWidgets.QPushButton(SimulationsDialog)
        self.browse_button.setObjectName("browse_button")
        self.form_layout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.browse_button)
        self.run_simulations_button = QtWidgets.QPushButton(SimulationsDialog)
        self.run_simulations_button.setObjectName("run_simulations_button")
        self.form_layout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.run_simulations_button)
        self.progress_bar = QtWidgets.QProgressBar(SimulationsDialog)
        self.progress_bar.setProperty("value", 24)
        self.progress_bar.setObjectName("progress_bar")
        self.form_layout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.progress_bar)
        self.buttonBox = QtWidgets.QDialogButtonBox(SimulationsDialog)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.form_layout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.buttonBox)
        self.vert_layout = QtWidgets.QVBoxLayout()
        self.vert_layout.setObjectName("vert_layout")
        self.form_layout.setLayout(10, QtWidgets.QFormLayout.SpanningRole, self.vert_layout)
        self.verticalLayout.addLayout(self.form_layout)

        self.retranslateUi(SimulationsDialog)
        self.buttonBox.accepted.connect(SimulationsDialog.accept)
        self.buttonBox.rejected.connect(SimulationsDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(SimulationsDialog)

    def retranslateUi(self, SimulationsDialog):
        _translate = QtCore.QCoreApplication.translate
        SimulationsDialog.setWindowTitle(_translate("SimulationsDialog", "Simulations"))
        self.label_2.setText(_translate("SimulationsDialog", "Number Of Parties:"))
        self.label_3.setText(_translate("SimulationsDialog", "Number Of Runs:"))
        self.generate_dataset_checkbox.setText(_translate("SimulationsDialog", "Generate Synthetic Dataset"))
        self.label.setText(_translate("SimulationsDialog", "Dataset:"))
        self.browse_button.setText(_translate("SimulationsDialog", "Browse..."))
        self.run_simulations_button.setText(_translate("SimulationsDialog", "Run Simulations"))
