# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI/UiFiles/UploadDataDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(QtCore.Qt.WindowModal)
        Dialog.resize(400, 300)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(30, 240, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(20, 10, 352, 223))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.guid_label = QtWidgets.QLabel(self.widget)
        self.guid_label.setObjectName("guid_label")
        self.gridLayout.addWidget(self.guid_label, 0, 0, 1, 1)
        self.guid_textbox = QtWidgets.QTextEdit(self.widget)
        self.guid_textbox.setObjectName("guid_textbox")
        self.gridLayout.addWidget(self.guid_textbox, 0, 1, 1, 1)
        self.data_label = QtWidgets.QLabel(self.widget)
        self.data_label.setObjectName("data_label")
        self.gridLayout.addWidget(self.data_label, 1, 0, 1, 1)
        self.browse_button = QtWidgets.QPushButton(self.widget)
        self.browse_button.setObjectName("browse_button")
        self.gridLayout.addWidget(self.browse_button, 1, 1, 1, 1)
        self.guid_label.raise_()
        self.data_label.raise_()
        self.browse_button.raise_()
        self.guid_textbox.raise_()

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Upload Data"))
        self.guid_label.setText(_translate("Dialog", "Experiment Guid: "))
        self.data_label.setText(_translate("Dialog", "Data:"))
        self.browse_button.setText(_translate("Dialog", "Browse..."))
